spring:
  config:
    import: "optional:classpath:none"  # MySQL config import 무시
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devnest;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.test.com
    port: 587
    username: test@test.com
    password: testpassword
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type: warn
    com.devnest: info
    org.springframework.security: debug 