spring:
  config:
    import: classpath:db.properties
  datasource:
    driver: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace