spring:
  config:
    import: classpath:db.properties
  datasource:
    driver: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace