server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  sql:
    init:
      mode: never
      
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: debug